basePath: /
definitions:
  models.ShowSubscSum:
    properties:
      end_date:
        type: string
      start_date:
        type: string
    type: object
  models.Subscription:
    properties:
      end_date:
        type: string
      id:
        type: integer
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      total_sum:
        type: integer
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для управления подписками.
  title: Subscriptions API
  version: "1.0"
paths:
  /subscriptions:
    get:
      description: Возвращает список подписок для пользователя, UUID берётся из заголовка
        Authorization.
      parameters:
      - description: User UUID
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список подписок
          schema:
            items:
              $ref: '#/definitions/models.Subscription'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить все подписки пользователя
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создаёт новую подписку. Все данные, включая user_id, передаются
        в теле запроса.
      parameters:
      - description: Данные новой подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.Subscription'
      produces:
      - application/json
      responses:
        "200":
          description: Подписка создана
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создать подписку
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      description: Удаляет запись подписки по её ID.
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Подписка удалена
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить подписку
      tags:
      - subscriptions
    get:
      description: Возвращает данные одной подписки по её ID.
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Данные подписки
          schema:
            $ref: '#/definitions/models.Subscription'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить подписку по ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: 'Обновляет запись подписки: указывается ID в пути и новые данные
        в теле запроса.'
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.Subscription'
      produces:
      - application/json
      responses:
        "200":
          description: Подписка обновлена
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновить подписку
      tags:
      - subscriptions
  /subscriptions/sum/{service}:
    post:
      consumes:
      - application/json
      description: Сервис указывается в пути, период (start_date и end_date) — в теле,
        user UUID — в заголовке Authorization.
      parameters:
      - description: User UUID
        in: header
        name: Authorization
        required: true
        type: string
      - description: Service name (например, Netflix)
        in: path
        name: service
        required: true
        type: string
      - description: Период в формате для примера {2025-08-01T00:00:00Z}
        in: body
        name: period
        required: true
        schema:
          $ref: '#/definitions/models.ShowSubscSum'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Subscription'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить подписки и их сумму по сервису за период
      tags:
      - subscriptions
swagger: "2.0"
